#!/bin/bash
if [ $1=="-p" ]
then
	if [ -z $2 ]
	then
		echo "time to percolate all modules"	
	else
		echo "percolating a selection of modules"
	fi
elif [ -d $1 ]
then
	DIR=$1
	REQ="requirements.txt"
	SLASH="/"
	echo $DIR | grep -qE "/$"
	if [ $? -eq 0 ]
	then
		DIR=$DIR
	else
		DIR=$DIR$SLASH
	fi
	
	
	#creating temporary environment
	mkvirtualenv temp
	if [ -f $DIR$REQ ];
	then
		pip install -r $DIR$REQ
	else
		filename=`date '+%y_%m_%d'`
		filename="temp$filename"
		touch $filename
		
		for file in `find $DIR -name "*.py"`
		do
			echo $file
			while read line
			do
				if echo $line | tr "\n" " " | grep -q "import"
				then
					replacement=""
					replace="\n"
					result=$(echo $line | sed 's/\n/$replacement/g')
					if [[ $result =~ .*"from".* ]]
					then
						module=`echo $result | sed -n 's/.*from \([a-zA-Z]*\) .*/\1/p'`
					else
						module=`echo $result | sed -n 's/.*import \([a-zA-Z]*\).*/\1/p'`
					fi
					pip install $module #sudo not needed because virtual env.
					echo $module >> $filename
				fi
			done < $file
		done
	fi
elif [ ! -d $1 ]
then
	echo "Invalid directory"
else
	echo "Invalid commands"
fi
