#!/bin/bash

#making sure that pip is installed
#wget https://bootstrap.pypa.io/get-pip.py
#python get-pip.py
#rm get-pip.py

filename=`date '+%y_%m_%d'`
filename="temp$filename"
touch $filename
for file in `find $1 -name "*.py"`
do
	echo $file
	while read line
	do
		if echo $line | tr "\n" " " | grep -q "import"
		then
			replacement=""
			replace="\n"
			result=$(echo $line | sed 's/\n/$replacement/g')
			if [[ $result =~ .*"from".* ]]
			then
				module=`echo $result | sed -n 's/.*from \([a-zA-Z]*\) .*/\1/p'`
			else
				module=`echo $result | sed -n 's/.*import \([a-zA-Z]*\).*/\1/p'`
			fi
			sudo pip install $module
			echo $module >> $filename
		fi
	done < $file
done
