#!/bin/bash


#wget https://bootstrap.pypa.io/get-pip.py

#python get-pip.py

#rm get-pip.py

for file in $1/*.py
do
	echo $file
	while read line
	do
		if echo $line | tr "\n" " " | grep -q "import"
			then
				replacement=""
				replace="\n"
				result=$(echo $line | sed 's/\n/$replacement/g')
				echo $result | sed -n 's/.*from \([a-zA-Z]*\) .*/\1/p'
				echo $result | sed -n 's/.*import \([a-zA-Z]*\).*/\1/p'
		fi
	done < $file
done
