#!/bin/bash

virtualenv=`whereis virtualenvwrapper.sh`
virtualenv=${virtualenv:19}

source $virtualenv 

if [ "$1" == "-p" ] #checks for flag
then
	if [ -z $2 ] 
	then
		for file in `pip freeze`
		do
		        rawr=`echo $file | grep -o '[A-Za-z_0-9]*=='`
	        	len=`expr ${#rawr} - 2`
	        	#sudo pip install ${rawr:0:$len}
		done
	else
		shift
		while test ${#} -gt 0
		do
			sudo pip install $1
			shift
		done
	fi
elif [ -d $1 ]
then
	DIR=`pwd`"/"$1
	REQ="requirements.txt"
	SLASH="/"
	echo $DIR | grep -qE "/$"
	if [ $? -eq 0 ]
	then
		DIR=$DIR
	else
		DIR=$DIR$SLASH
	fi
	
	#creating temporary environment
	mkvirtualenv temp
	workon temp
	if [ -f $DIR$REQ ];
	then
		pip install -r $DIR$REQ
	else
		for file in `find $DIR -name "*.py"`
		do
			echo $file
			while read line
			do
				if echo $line | tr "\n" " " | grep -q "import"
				then
					replacement=""
					replace="\n"
					result=$(echo $line | sed 's/\n/$replacement/g')
					if [[ $result =~ .*"from".* ]]
					then
						module=`echo $result | sed -n 's/.*from \([a-zA-Z]*\) .*/\1/p'`
					else
						module=`echo $result | sed -n 's/.*import \([a-zA-Z]*\).*/\1/p'`
					fi
					pip install $module #sudo not needed because virtual env.
				fi
			done < $file
		done
	fi
elif [ ! -d $1 ]
then
	echo "Invalid directory"
else
	echo "Invalid commands"
fi
